XBB/Xqiye/config/routes.rb
Rails.application.routes.draw do


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :workeraccounts

  resources :workeraccounts do 
    member do 
      get 'reset'=>'workeraccounts#reset' ,:as =>'reset_password'
      #put :change_current_city
    end
  end

  resources :stations do
  	collection do
  		get :suggestion
  	end
  end

  resources :couriers

  resources :factories

  resources :worker_messages

  root 'workeraccounts#index'

end

XBB/Xqiye/app/models/workeraccount.rb
class Workeraccount < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :lockable
end

XBB/Xqiye/app/controllers/workeraccounts_controller.rb
class WorkeraccountsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_workeraccount, only: [:show,:edit,:update,:destroy,:reset]
  before_filter :authenticate_workeraccount!
  def index
    #@workers = Workeraccount.all
    @workeraccounts = Workeraccount.paginate(page: params[:page], per_page: 10).order(updated_at: :desc)
  end

  def show
  end

  def new
    @workeraccount = Workeraccount.new
  end

  def create
    @workeraccount = Workeraccount.new(workeraccount_params)

    respond_to do |format|
      if @workeraccount.save
        format.html { redirect_to workeraccounts_path, notice: 'Workeraccount was successfully created.' }
        format.json { render :show, status: :created, location: @workeraccount }
      else
        format.html { render :new }
        format.json { render json: @workeraccount.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end
  def reset
  	
  end

  def update
    respond_to do |format|
      if @workeraccount.update(workeraccount_params)

        format.html { redirect_to workeraccounts_path, notice: 'Workeraccount was successfully updated.' }
        format.json { render :show, status: :ok, location: @workeraccount }
      else
        format.html { render :reset }
        format.json { render json: @workeraccount.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  	  def set_workeraccount
      	@workeraccount = Workeraccount.find(params[:id])
      end
  	  def workeraccount_params
  		  params.require(:workeraccount).permit(:email, :password, :password_confirmation)
  	  end

end

XBB/Xqiye/app/views/workeraccounts/edit.html.erb
<h1>Edit</h1>
<%= simple_form_for(@wrokeraccount,html: { method: :put }) do  |f|%>
	<%= f.error_notification%>
	<div class="form-inputs">
	    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
	    <%= f.input :password_confirmation, required: true %>    
	</div>
	<div class="form-acions">
	<%= f.button :submit%>
	</div>
<% end %>

<%= link_to 'Back',workeraccounts_path%>

XBB/Xqiye/app/views/workeraccounts/index.html.erb
<div  class="panel panel-default">
	<div class="panel-heading">操作员</div>
	<div class="panel-body">
		<table class="table table table-striped" width='600px'>
			<thead>
				<tr>
					<th>登录邮箱</th>
					<th>登录次数</th>
					<th>上次登录时间</th>
					<th>上次登录IP</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @workeraccounts.each do |account|%>
				<tr>
					<td><%= account.email %></td>
					<td><%= account.sign_in_count%></td>
					<td><%= account.last_sign_in_at%> </td>
					<td><%= account.last_sign_in_ip%> </td>
					<td></td>
					<td><%= link_to '修改密码',reset_password_workeraccount_path(account)%></td>
					<td><%= link_to '修改',edit_workeraccount_path(account)%></td>
				</tr>
				<%end%>
			</tbody>
		</table>		
	</div>
	<div class="panel-footer">
		<%= link_to '新建', new_workeraccount_path, class: 'btn btn-info btn-sm'%>
	</div>

</div>

XBB/Xqiye/app/views/workeraccounts/new.html.erb
<h1>New WorkerAccount</h1>
<%= simple_form_for(@workeraccount) do |f|%>
	<%= f.error_notification%>
	<div class="form-inputs">
		<%= f.input :email, required: false, autofocus: true%>
	    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
	    <%= f.input :password_confirmation, required: true %>
	    
	</div>
	<div class="form-acions">
		<%= f.button :submit%>
	</div>
	<%= link_to 'Back',workeraccounts_path%>
<% end %>

XBB/Xqiye/app/views/workeraccounts/reset.html.erb
<h1>Reset Password</h1>
<%= simple_form_for(@workeraccount,url:workeraccount_path(@workeraccount),html: { method: :put }) do |f|%>
	<%= f.error_notification %>
	<div class="form-inputs">
	    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
		    <%= f.input :password_confirmation, required: true %>
	    </div>

	    <div class="form-actions">
	        <%= f.button :submit,"Change my password" %>
	    </div>
	
<% end %>
<%= link_to 'Back',workeraccounts_path%>

XBB/Xqiye/app/views/workeraccounts/show.html.erb
<html>
	
	show
</html>