XBB/Xqiye/config/routes.rb
Rails.application.routes.draw do


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :workeraccounts

  resources :workeraccounts do 
    member do 
      get 'reset'=>'workeraccounts#reset' ,:as =>'reset_password'
      #put :change_current_city
    end
  end

  resources :stations do
  	collection do
  		get :suggestion
  	end
  end

  resources :couriers

  resources :factories

  resources :worker_messages

  root 'workeraccounts#index'

end

XBB/Xqiye/app/models/worker_message.rb
class WorkerMessage < ApplicationRecord
	  #validate message
  # validates_presence_of :worker_id,:message =>"工号必须写"
  validates :worker_id, presence:true
  validates :worker_name, presence:true
  # validates_format_of :role, :with=>/["请选择"]/, :message=>"qinn"

end

XBB/Xqiye/app/controllers/worker_messages_controller.rb
class WorkerMessagesController < ApplicationController
  before_filter :authenticate_workeraccount!
  before_action :set_worker_message, only: [:show, :edit, :update, :destroy]

  # GET /worker_messages
  # GET /worker_messages.json
  def index
    @worker_messages = WorkerMessage.all
  end

  # GET /worker_messages/1
  # GET /worker_messages/1.json
  def show
  end

  # GET /worker_messages/new
  def new
    @worker_message = WorkerMessage.new
  end

  # GET /worker_messages/1/edit
  def edit
  end

  # POST /worker_messages
  # POST /worker_messages.json
  def create
    @worker_message = WorkerMessage.new(worker_message_params)

    respond_to do |format|
      if @worker_message.save
        format.html { redirect_to @worker_message, notice: 'Worker message was successfully created.' }
        format.json { render :show, status: :created, location: @worker_message }
      else
        format.html { render :new }
        format.json { render json: @worker_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worker_messages/1
  # PATCH/PUT /worker_messages/1.json
  def update
    respond_to do |format|
      if @worker_message.update(worker_message_params)
        format.html { redirect_to @worker_message, notice: 'Worker message was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker_message }
      else
        format.html { render :edit }
        format.json { render json: @worker_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worker_messages/1
  # DELETE /worker_messages/1.json
  def destroy
    @worker_message.destroy
    respond_to do |format|
      format.html { redirect_to worker_messages_url, notice: 'Worker message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker_message
      @worker_message = WorkerMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_message_params
      params.require(:worker_message).permit(:worker_id, :worker_name, :sex, :age, :birthday, :role, :academic, :factory_id, :region, :delFlag, :S_01, :S_o2)
    end
end

XBB/Xqiye/app/helpers/worker_messages_helper.rb
module WorkerMessagesHelper
end

XBB/Xqiye/app/views/worker_messages/_form.html.erb
<%= form_for(worker_message) do |f| %>
  <% if worker_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker_message.errors.count, "error") %> prohibited this worker_message from being saved:</h2>

      <ul>
      <% worker_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :worker_id %>
    <%= f.text_field :worker_id %>
  </div>

  <div class="field">
    <%= f.label :worker_name %>
    <%= f.text_field :worker_name %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.select :sex, options_for_select([  ['男','男'], ['女', '女']])%> 
  
  </div>
  </div>

  <div class="field" style="display:none">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select :birthday , :start_year=>1980%>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.select :role, options_for_select([ ['请选择','请选择'],['管理员','管理员'], ['取送人员', '取送人员'], ['加工厂人员', '加工厂人员'], ['管理员4', '管理员4'] ])%>
  </div>

  <div class="field">
    <%= f.label :academic %>
    <%= f.select :academic, options_for_select([['请选择','请选择'], ['大专','大专'], ['本科毕业', '本科毕业'], ['本科结业', '本科结业'], ['本科及以上', '本科及以上'] ])%>
  </div>

  <div class="field">
    <%= f.label :factory_id %>
    <%= f.number_field :factory_id %>
  </div>

  <div class="field">
    <%= f.label :region %>
    <%= f.text_field :region %>
  </div>

  <div class="field" style="display:none">
    <%= f.label :delFlag %>
    <%= f.text_field :delFlag %>
  </div>

  <div class="field" style="display:none">
    <%= f.label :S_01 %>
    <%= f.text_field :S_01 %>
  </div>

  <div class="field" style="display:none">
 
    <%= f.label :S_o2 %>
    <%= f.text_field :S_o2 %>
    
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

XBB/Xqiye/app/views/worker_messages/edit.html.erb
<h1>Editing Worker Message</h1>

<%= render 'form', worker_message: @worker_message %>

<%= link_to 'Show', @worker_message %> |
<%= link_to 'Back', worker_messages_path %>

XBB/Xqiye/app/views/worker_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>员工信息</h1>

<table width="800px" border="1">
  <thead>
    <tr>
      <th>Worker</th>
      <th>Worker name</th>
      <th>Sex</th>
      <th style="display:none">Age</th>
      <th>Birthday</th>
      <th>Role</th>
      <th>Academic</th>
      <th>Factory</th>
      <th>Region</th>
      <th style="display:none">Delflag</th>
      <th style="display:none">S 01</th>
      <th style="display:none">S o2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worker_messages.each do |worker_message| %>
      <tr>
        <td><%= worker_message.worker_id %></td>
        <td><%= worker_message.worker_name %></td>
        <td><%= worker_message.sex %></td> 
        <td style="display:none"><%= worker_message.age %></td> 
        <td><%= worker_message.birthday %></td>
        <td><%= worker_message.role %></td>
        <td><%= worker_message.academic %></td>
        <td><%= worker_message.factory_id %></td>
        <td><%= worker_message.region %></td>
        <td style="display:none"><%= worker_message.delFlag %></td>
        <td style="display:none"><%= worker_message.S_01 %></td>
        <td style="display:none"><%= worker_message.S_o2 %></td>
        <td><%= link_to 'Show', worker_message %></td>
        <td><%= link_to 'Edit', edit_worker_message_path(worker_message) %></td>
        <td><%= link_to 'Destroy', worker_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker Message', new_worker_message_path %>

XBB/Xqiye/app/views/worker_messages/new.html.erb
<h1>New Worker Message</h1>

<%= render 'form', worker_message: @worker_message %>

<%= link_to 'Back', worker_messages_path %>

XBB/Xqiye/app/views/worker_messages/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>详细信息展示</strong>
</p>

<p>
  <strong>Worker id:</strong>
  <%= @worker_message.worker_id %>
</p>

<p>
  <strong>Worker name:</strong>
  <%= @worker_message.worker_name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @worker_message.sex %>
</p>

<p>
  <strong style="display:none">Age:</strong>
  <%= @worker_message.age %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @worker_message.birthday %>
</p>

<p>
  <strong>Role:</strong>
  <%= @worker_message.role %>
</p>

<p>
  <strong>Academic:</strong>
  <%= @worker_message.academic %>
</p>

<p>
  <strong>Factory:</strong>
  <%= @worker_message.factory_id %>
</p>

<p>
  <strong>Region:</strong>
  <%= @worker_message.region %>
</p>

<p style="display:none">
  <strong>Delflag:</strong>
  <%= @worker_message.delFlag %>
</p>

<p style="display:none">
  <strong>S 01:</strong>
  <%= @worker_message.S_01 %>
</p>

<p style="display:none">
  <strong>S o2:</strong>
  <%= @worker_message.S_o2 %>
</p>

<%= link_to 'Edit', edit_worker_message_path(@worker_message) %> |
<%= link_to 'Back', worker_messages_path %>