XBB/Xqiye/config/routes.rb
Rails.application.routes.draw do


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :workeraccounts

  resources :workeraccounts do 
    member do 
      get 'reset'=>'workeraccounts#reset' ,:as =>'reset_password'
      #put :change_current_city
    end
  end

  resources :stations do
  	collection do
  		get :suggestion
  	end
  end

  resources :couriers

  resources :factories

  resources :worker_messages

  root 'workeraccounts#index'

end

XBB/Xqiye/app/models/station.rb
class Station < ApplicationRecord
	has_and_belongs_to_many :couriers
	has_and_belongs_to_many :factories

	belongs_to :region
end

XBB/Xqiye/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  #load_and_authorize_resource

  before_action :set_station, only: [:show, :edit, :update, :destroy]
  
  before_filter :authenticate_workeraccount!  
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def suggestion
    url = 'http://api.map.baidu.com/place/v2/suggestion'
    resp = RestClient.get url, {params: {region: '全国', output: 'json', ak: 'vjbRxDq3n76sM7PqXFuOwibmqZvIYPRN', query: params[:term]}}

    result = JSON.parse(resp)['result'].map do |result|
      city = Region.find_by_name_and_level(result['city'],2)
      area = city.children.find_by_name(result['district'])
      {id: result['name'], text: result['name'], lat: result['location']['lat'], lng: result['location']['lng'],region_id:area.id}


    end
    
    render json: {results: result}
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :address, :comment, :lat, :lng,:region_id)
    end
end

XBB/Xqiye/app/helpers/stations_helper.rb
module StationsHelper
end

XBB/Xqiye/app/views/stations/_form.html.slim
= simple_form_for(@station) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :address, as: :select
    = f.input :comment
    = f.input :lat
    = f.input :lng
    = f.association :region, as: :string

  .form-actions
    = f.button :submit

javascript:
  $(function(){
    $("#station_address").select2({
      placeholder: "请输入地址",
      theme: 'bootstrap',
      ajax: {
        url: '/stations/suggestion.json',
        dataType: 'json',
        delay: 250,
        cache: false
      },
      minimumInputLength: 1
    })

    $("#station_address").on("change", function (e) {
      var data = $("#station_address").select2('data')[0];
      if(data){
        $("#station_lat").val(data['lat'])
        $("#station_lng").val(data['lng']) 
        $("#station_region_id").val(data['region_id'])
      }
    });
  })

XBB/Xqiye/app/views/stations/edit.html.slim
h1 Editing station

== render 'form'

= link_to 'Show', @station
'  |
= link_to 'Back', stations_path

XBB/Xqiye/app/views/stations/index.html.slim
h1 Listing stations

table.table.table-stripted
  thead
    tr
      th Name
      th Address
      th Comment
      th Lat
      th Lng
      th
      th
      th

  tbody
    - @stations.each do |station|
      tr
        td = station.name
        td = station.address
        td = station.comment
        td = station.lat
        td = station.lng
        td = link_to 'Show', station
        td = link_to 'Edit', edit_station_path(station)
        td = link_to 'Destroy', station, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Station', new_station_path

XBB/Xqiye/app/views/stations/new.html.slim
h1 New station

== render 'form'

= link_to 'Back', stations_path

XBB/Xqiye/app/views/stations/show.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 基本信息
      .panel-body
        table.table.table-striped  style="border:#cccccc solid 1px;"
          tr 
            td width='15%' style="border:#cccccc solid 1px;" 
              b Name 
            td width='35%' style="border:#cccccc solid 1px;" = @station.name
            td width='15%' style="border:#cccccc solid 1px;" 
              b Address
            td width='35%' style="border:#cccccc solid 1px;" = @station.address
        
          tr 
            td width='15%' style="border:#cccccc solid 1px;" 
              b Lat
            td width='35%' style="border:#cccccc solid 1px;" = @station.lat
            td width='15%' style="border:#cccccc solid 1px;"
              b Lng
            td width='35%' style="border:#cccccc solid 1px;" = @station.lng
          tr 
            
            td width='15%' style="border:#cccccc solid 1px;" 
              b Comment
            td width='35%' style="border:#cccccc solid 1px;" = @station.comment
            td width='15%' style="border:#cccccc solid 1px;" 
              b Region
            td width='35%' style="border:#cccccc solid 1px;" = @station.region_id

= link_to 'Edit', edit_station_path(@station)
'  |
= link_to 'Back', stations_path