XBB/Xqiye/config/routes.rb
Rails.application.routes.draw do


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :workeraccounts

  resources :workeraccounts do 
    member do 
      get 'reset'=>'workeraccounts#reset' ,:as =>'reset_password'
      #put :change_current_city
    end
  end

  resources :stations do
  	collection do
  		get :suggestion
  	end
  end

  resources :couriers

  resources :factories

  resources :worker_messages

  root 'workeraccounts#index'

end

XBB/Xqiye/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default " role="navigation" >
	<div class="navbar-static-top">
	    <div class="container" style="background:#F8F8F8">
	    	<a class="navbar-brand" href="" style="text-decoration:none" >后台</a>
	    	<%if current_workeraccount%>
		    	<div class="navbar-collapse collapse navbar-responsive-collapse"  >	
		    		<ul class="nav navbar-nav">
		    			<li class="dropdown">
		    				<%= link_to "系统管理<b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', data: {toggle: 'dropdown'} %>
		    				<ul class="dropdown-menu">
		    					<li >
		    						<%= link_to "人员",workeraccounts_path %>
		    					</li>
		    					<li >
		    						<%= link_to "角色",workeraccounts_path %>
		    					</li>
		    					<li >
		    						<%= link_to "员工信息",worker_messages_path %>
		    					</li>
		    				</ul>
		    			</li>
		    			<li class="dropdown">
		    				<%= link_to "总部管理<b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', data: {toggle: 'dropdown'} %>
		    				<ul class="dropdown-menu">
		    					<li >
		    						<%= link_to "开通城市",workeraccounts_path %>
		    					</li>
		    					<li >
		    						<%= link_to "品类",workeraccounts_path %>
		    					</li>
		    				</ul>
		    			</li>
		    			<li class="dropdown">
		    				<%= link_to "分城市管理<b class='caret'></b>".html_safe, '#', :class => 'dropdown-toggle', data: {toggle: 'dropdown'} %>
		    				<ul class="dropdown-menu">
		    					<li >
		    						<%= link_to "驿站",stations_path %>
		    					</li>
		    					<li >
		    						<%= link_to "取送人员",couriers_path %>
		    					</li>
		    					<li >
		    						<%= link_to "工厂",factories_path %>
		    					</li>
		    				</ul>
		    			</li>
		    			
		    		</ul>
		    		<ul class="nav navbar-nav ieCss pull-right" role="presentation" >
						<span style="font-size:14px; color:#777" >
						<%= current_workeraccount.email %>
			    		<%= link_to "退出登陆",  destroy_workeraccount_session_path , method: :delete %>
				        </span>
				    </ul>
		    	</div>
		    	
		    	
	    	<%end%>
	    </div>
    </div>
</nav>

XBB/Xqiye/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title> 后台</title>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render "layouts/menu"%>
  	<div class="container" id="container">
      <%= bootstrap_flash %>
      <%= yield %>
    
    </div>

  </body>
</html>